#area and perimeter of a rect,circle,sqare,parellelogram,trapizium
print("rectangle l and b")
l=eval(input())
b=eval(input())
print("area of rectangle",(l*b))
print("perimeter of rectangle",(2*(l+b)))
print("square side")
a=eval(input())
print("area of square",(a*a))
print("perimeter of circle",(4*a))
print("circle radius")
r=eval(input())
print("area of circle",(3.14*r*r))
print("perimeter of circle",(2*3.14*r))
print("triangle base and height")
base=eval(input())
height=eval(input())
print("area of triangle",((1/2)*base*height))
print("area of parallelogram",(base*height))
print("trapezium height and lenghts")
h=eval(input())
l1=eval(input())
l2=eval(input())
print("area of trapezium",(1/2)*h*(l1-l2))
